# Generated by Django 6.0.1 on 2026-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_gatein', '0010_alter_constructiongateentry_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructiongateentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
