# Generated by Django 6.0.1 on 2026-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_gatein', '0008_alter_maintenancegateentry_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancegateentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
