# Generated by Django 6.0.1 on 2026-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_needs_gatein', '0011_alter_dailyneedgateentry_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyneedgateentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
